apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: raghav141988/java-server
          ports:
            - containerPort: 8080
          env:
            - name: MONGODB_HOST
              value: mango-cluster-ip-service
            #- name: CLIENT_SECRET
              #valueFrom:
                #secretKeyRef:
                  #name: clientsecret
                  #key: CLIENT_SECRET
        
